### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by ashra-f** [ashra-f/Job-Processor-Sim#1]
- [x] Program breaking after initial process button click
- [x] Rearrange buttons
- [x] Missing data in metrics block
- [x] Add feature to disable last clicked proc button
