### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by ashra-f** [ashra-f/Job-Processor-Sim#2]
- [ ] sim is slow with large numbers (>100 time units)
- [ ] clean code: js, html, css
- [ ] have chart refresh
- [ ] option to download file of all lines of sim (10,000 time units)
